[project]
name = "python-for-chemists"
version = "0.1.0"
description = "Python for Chemists SS26"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-book>=2.0.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "rdkit>=2025.9.6",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
]

[project.scripts]
generate-student-notebooks = "scripts.generate_student_notebooks:main"
